# 1. Import the Azure module installed on the server
Import-Module Az.Storage

# 2. Define Azure infrastructure details
$ResourceGroup = "Portfolio-RG"
$StorageAccountName = "YOUR_STORAGE_ACCOUNT_NAME_HERE" # Put your unique storage account name here
$ContainerName = "serverbackups"

# 3. Target today's local log file generated by the health script
$CurrentDate = Get-Date -Format "yyyy-MM-dd"
$LocalFile = "C:\ServerLogs\HealthReport_$CurrentDate.csv"

# 4. Authenticate securely using your specific Azure Tenant ID (Handles MFA/Conditional Access)
Write-Host "Please authenticate your Azure account..." -ForegroundColor Yellow
Connect-AzAccount -UseDeviceAuthentication -TenantId "YOUR-AZURE-TENANT-ID-HERE"

# 5. Connect to your specific storage account context
$StorageContext = (Get-AzStorageAccount -ResourceGroupName $ResourceGroup -Name $StorageAccountName).Context

# 6. Upload the file to your Azure Blob Container
Write-Host "Uploading $LocalFile to Azure Container: $ContainerName..." -ForegroundColor Cyan
Set-AzStorageBlobContent -File $LocalFile -Container $ContainerName -Blob "HealthReport_$CurrentDate.csv" -Context $StorageContext -Force

Write-Host "Success! Check your Azure portal Container to see your file." -ForegroundColor Green
